import 'package:drift/drift.dart';
import 'package:afterclose/data/database/app_database.dart';

/// 事件行事曆相關資料存取
extension EventDao on AppDatabase {
  // ==========================================
  // 事件行事曆操作（Phase 4.3）
  // ==========================================

  /// 取得日期範圍內的事件
  Future<List<StockEventEntry>> getEventsInRange(
    DateTime start,
    DateTime end, {
    List<String>? symbols,
  }) {
    final query = select(stockEvent)
      ..where(
        (t) =>
            t.eventDate.isBiggerOrEqualValue(start) &
            t.eventDate.isSmallerOrEqualValue(end),
      )
      ..orderBy([(t) => OrderingTerm.asc(t.eventDate)]);

    if (symbols != null && symbols.isNotEmpty) {
      query.where((t) => t.symbol.isIn(symbols) | t.symbol.isNull());
    }

    return query.get();
  }

  /// 新增事件
  Future<int> insertStockEvent(StockEventCompanion entry) {
    return into(stockEvent).insert(entry);
  }

  /// 刪除事件
  Future<void> deleteStockEvent(int id) {
    return (delete(stockEvent)..where((t) => t.id.equals(id))).go();
  }

  /// 刪除系統自動產生的事件（用於重新同步）
  Future<void> deleteAutoGeneratedEvents() {
    return (delete(
      stockEvent,
    )..where((t) => t.isAutoGenerated.equals(true))).go();
  }

  /// 取得指定 symbol 的所有事件
  Future<List<StockEventEntry>> getEventsForSymbol(String symbol) {
    return (select(stockEvent)
          ..where((t) => t.symbol.equals(symbol))
          ..orderBy([(t) => OrderingTerm.asc(t.eventDate)]))
        .get();
  }
}
