import 'package:drift/drift.dart';
import 'package:intl/intl.dart';

import 'package:afterclose/core/exceptions/app_exception.dart';
import 'package:afterclose/core/utils/logger.dart';
import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/data/remote/tpex_client.dart';
import 'package:afterclose/data/remote/twse_client.dart';

/// 已宣告股利 + 股東會同步器
///
/// 從 TWSE/TPEX OpenAPI 取得已宣告股利資料和股東會日程：
/// 1. 將股利資料 upsert 至 DividendHistory（更新 exDividendDate/exRightsDate）
/// 2. 將股東會日程寫入 StockEvent（eventType = SHAREHOLDER_MEETING）
///
/// 此同步器在 UpdateService._syncAuxiliaryData() 中呼叫，
/// 與 MarketIndexSyncer、TdccHoldingSyncer 同級。
class DividendSyncer {
  DividendSyncer({
    required AppDatabase database,
    TwseClient? twseClient,
    TpexClient? tpexClient,
  }) : _db = database,
       _twse = twseClient,
       _tpex = tpexClient;

  final AppDatabase _db;
  final TwseClient? _twse;
  final TpexClient? _tpex;

  static final _dateFormat = DateFormat('yyyy-MM-dd');

  /// 同步已宣告股利 + 股東會日程
  ///
  /// 回傳同步結果，包含 upsert 筆數和事件數。
  /// 各資料來源獨立 try/catch，單一來源失敗不影響其他。
  Future<DividendSyncResult> sync() async {
    var dividendsUpserted = 0;
    var meetingEventsCreated = 0;
    final errors = <String>[];

    // 取得 DB 中所有已知股票（FK constraint — 過濾 1101B 等特別股）
    final knownStocks = await _db.getAllActiveStocks();
    final knownSymbols = knownStocks.map((s) => s.symbol).toSet();

    // ==================================================
    // Phase 1: 取得已宣告股利 → upsert DividendHistory
    // ==================================================
    final dividendCompanions = <DividendHistoryCompanion>[];
    final meetingCompanions = <StockEventCompanion>[];

    // 1a. TWSE 已宣告股利（上市）
    if (_twse != null) {
      try {
        final twseData = await _twse.getDeclaredDividends();
        for (final item in twseData) {
          if (!knownSymbols.contains(item.symbol)) continue;

          dividendCompanions.add(
            _toDividendCompanion(
              symbol: item.symbol,
              year: item.dividendYear,
              cashDividend: item.cashDividend,
              stockDividend: item.stockDividend,
              exDividendDate: item.exDividendDate,
              exRightsDate: item.exRightsDate,
            ),
          );

          // 從 TWSE 資料提取股東會日期（Feature 3）
          if (item.shareholderMeetingDate != null) {
            meetingCompanions.add(
              StockEventCompanion.insert(
                symbol: Value(item.symbol),
                eventType: 'SHAREHOLDER_MEETING',
                eventDate: item.shareholderMeetingDate!,
                title: '${item.symbol} ${item.companyName} 股東會',
                description: const Value(null),
                isAutoGenerated: const Value(true),
              ),
            );
          }
        }
        AppLogger.info('DividendSyncer', 'TWSE 已宣告股利: ${twseData.length} 筆');
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TWSE 已宣告股利同步失敗', e);
        errors.add('TWSE 已宣告股利: $e');
      }
    }

    // 1b. TPEX 已宣告股利（上櫃）
    if (_tpex != null) {
      try {
        final tpexData = await _tpex.getDeclaredDividends();
        for (final item in tpexData) {
          if (!knownSymbols.contains(item.symbol)) continue;

          dividendCompanions.add(
            _toDividendCompanion(
              symbol: item.symbol,
              year: item.dividendYear,
              cashDividend: item.cashDividend,
              stockDividend: item.stockDividend,
              exDividendDate: item.exDividendDate,
              exRightsDate: item.exRightsDate,
            ),
          );
        }
        AppLogger.info('DividendSyncer', 'TPEX 已宣告股利: ${tpexData.length} 筆');
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TPEX 已宣告股利同步失敗', e);
        errors.add('TPEX 已宣告股利: $e');
      }
    }

    // ==================================================
    // Phase 2: Upsert DividendHistory
    // ==================================================
    if (dividendCompanions.isNotEmpty) {
      try {
        await _db.insertDividendData(dividendCompanions);
        dividendsUpserted = dividendCompanions.length;
        AppLogger.info('DividendSyncer', '股利資料 upsert: $dividendsUpserted 筆');
      } catch (e) {
        AppLogger.warning('DividendSyncer', '股利資料寫入失敗', e);
        errors.add('DB 寫入: $e');
      }
    }

    // ==================================================
    // Phase 3: 取得股東會日程（TPEX ap41_O）
    // ==================================================
    if (_tpex != null) {
      try {
        final meetings = await _tpex.getShareholderMeetings();
        for (final meeting in meetings) {
          if (!knownSymbols.contains(meeting.symbol)) continue;

          meetingCompanions.add(
            StockEventCompanion.insert(
              symbol: Value(meeting.symbol),
              eventType: 'SHAREHOLDER_MEETING',
              eventDate: meeting.meetingDate,
              title:
                  '${meeting.symbol} ${meeting.companyName} ${meeting.meetingType}',
              description: Value(_buildMeetingDescription(meeting)),
              isAutoGenerated: const Value(true),
            ),
          );
        }
        AppLogger.info('DividendSyncer', 'TPEX 股東會: ${meetings.length} 筆');
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TPEX 股東會同步失敗', e);
        errors.add('TPEX 股東會: $e');
      }
    }

    // ==================================================
    // Phase 4: 寫入股東會 StockEvent（去重後）
    // ==================================================
    if (meetingCompanions.isNotEmpty) {
      try {
        // 去重：同一 symbol + 同一日期只保留一筆（TWSE 和 TPEX 可能重複）
        final uniqueMeetings = _deduplicateEvents(meetingCompanions);

        await _db.transaction(() async {
          // 只刪除 SHAREHOLDER_MEETING 類型的自動事件，不影響其他
          await _db.deleteAutoGeneratedEventsByTypes(const [
            'SHAREHOLDER_MEETING',
          ]);
          for (final companion in uniqueMeetings) {
            await _db.insertStockEvent(companion);
          }
        });
        meetingEventsCreated = uniqueMeetings.length;
        AppLogger.info('DividendSyncer', '股東會事件寫入: $meetingEventsCreated 筆');
      } catch (e) {
        AppLogger.warning('DividendSyncer', '股東會事件寫入失敗', e);
        errors.add('股東會事件: $e');
      }
    }

    return DividendSyncResult(
      dividendsUpserted: dividendsUpserted,
      meetingEventsCreated: meetingEventsCreated,
      errors: errors,
    );
  }

  /// 建立 DividendHistoryCompanion
  DividendHistoryCompanion _toDividendCompanion({
    required String symbol,
    required int year,
    required double cashDividend,
    required double stockDividend,
    DateTime? exDividendDate,
    DateTime? exRightsDate,
  }) {
    return DividendHistoryCompanion(
      symbol: Value(symbol),
      year: Value(year),
      cashDividend: Value(cashDividend),
      stockDividend: Value(stockDividend),
      exDividendDate: Value(
        exDividendDate != null ? _dateFormat.format(exDividendDate) : null,
      ),
      exRightsDate: Value(
        exRightsDate != null ? _dateFormat.format(exRightsDate) : null,
      ),
    );
  }

  /// 建立股東會事件描述
  String? _buildMeetingDescription(TpexShareholderMeeting meeting) {
    final parts = <String>[];
    if (meeting.location != null) parts.add(meeting.location!);
    if (meeting.hasBoardElection) parts.add('改選董監事');
    if (meeting.hasEVoting) parts.add('電子投票');
    return parts.isEmpty ? null : parts.join(' | ');
  }

  /// 去重：同一 symbol + 同一日期 + 同一 eventType 只保留一筆
  List<StockEventCompanion> _deduplicateEvents(
    List<StockEventCompanion> companions,
  ) {
    final seen = <String>{};
    final result = <StockEventCompanion>[];
    for (final c in companions) {
      final sym = c.symbol.value ?? '';
      final date = c.eventDate.value;
      final type = c.eventType.value;
      final key = '${sym}_${date.year}${date.month}${date.day}_$type';
      if (seen.add(key)) {
        result.add(c);
      }
    }
    return result;
  }
}

/// 股利同步結果
class DividendSyncResult {
  const DividendSyncResult({
    this.dividendsUpserted = 0,
    this.meetingEventsCreated = 0,
    this.errors = const [],
  });

  final int dividendsUpserted;
  final int meetingEventsCreated;
  final List<String> errors;

  bool get hasErrors => errors.isNotEmpty;
}
