import 'package:drift/drift.dart';
import 'package:intl/intl.dart';

import 'package:afterclose/core/utils/logger.dart';
import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/domain/repositories/event_repository.dart';

/// 事件日曆 Repository
///
/// 管理行事曆事件，包括使用者自訂事件與系統自動產生的除權息事件。
class EventRepository implements IEventRepository {
  EventRepository({required AppDatabase database}) : _db = database;

  final AppDatabase _db;

  static final _dateFormat = DateFormat('yyyy-MM-dd');

  // ==================================================
  // 事件查詢
  // ==================================================

  /// 取得指定日期範圍內的事件
  @override
  Future<List<StockEventEntry>> getEventsInRange(
    DateTime start,
    DateTime end, {
    List<String>? symbols,
  }) {
    return _db.getEventsInRange(start, end, symbols: symbols);
  }

  /// 取得指定 symbol 的所有事件
  @override
  Future<List<StockEventEntry>> getEventsForSymbol(String symbol) {
    return _db.getEventsForSymbol(symbol);
  }

  // ==================================================
  // 事件操作
  // ==================================================

  /// 新增自訂事件
  @override
  Future<int> addCustomEvent({
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) {
    return _db.insertStockEvent(
      StockEventCompanion.insert(
        symbol: Value(symbol),
        eventType: 'CUSTOM',
        eventDate: eventDate,
        title: title,
        description: Value(description),
      ),
    );
  }

  /// 刪除事件
  @override
  Future<void> deleteEvent(int id) {
    return _db.deleteStockEvent(id);
  }

  // ==================================================
  // 除權息日同步
  // ==================================================

  /// 從 DividendHistory 同步除權息事件
  ///
  /// 流程：
  /// 1. 取得自選股 + 持倉股的 symbol
  /// 2. 從 DividendHistory 取得有除權息日期的紀錄，收集所有待插入事件
  /// 3. 在單一交易中：刪除舊的自動事件 → 批次插入新事件
  @override
  Future<int> syncDividendEvents() async {
    // 1. 取得所有相關 symbol（自選股 + 持倉股）
    final watchlistEntries = await _db.getWatchlist();
    final portfolioPositions = await _db.getPortfolioPositions();

    final symbols = <String>{
      ...watchlistEntries.map((e) => e.symbol),
      ...portfolioPositions.map((e) => e.symbol),
    };

    if (symbols.isEmpty) return 0;

    // 2. 收集所有待插入的事件（在交易外讀取）
    final companions = <StockEventCompanion>[];
    for (final symbol in symbols) {
      final dividends = await _db.getDividendHistory(symbol);

      for (final div in dividends) {
        // 除息日
        if (div.exDividendDate != null && div.exDividendDate!.isNotEmpty) {
          final date = _tryParseDate(div.exDividendDate!);
          if (date != null) {
            companions.add(
              StockEventCompanion.insert(
                symbol: Value(symbol),
                eventType: 'EX_DIVIDEND',
                eventDate: date,
                title: '$symbol 除息',
                description: Value(
                  '現金股利 ${div.cashDividend.toStringAsFixed(2)} 元',
                ),
                isAutoGenerated: const Value(true),
              ),
            );
          }
        }

        // 除權日
        if (div.exRightsDate != null && div.exRightsDate!.isNotEmpty) {
          final date = _tryParseDate(div.exRightsDate!);
          if (date != null) {
            companions.add(
              StockEventCompanion.insert(
                symbol: Value(symbol),
                eventType: 'EX_RIGHTS',
                eventDate: date,
                title: '$symbol 除權',
                description: Value(
                  '股票股利 ${div.stockDividend.toStringAsFixed(2)} 元',
                ),
                isAutoGenerated: const Value(true),
              ),
            );
          }
        }
      }
    }

    // 3. 在單一交易中刪除舊事件並批次插入新事件
    await _db.transaction(() async {
      await _db.deleteAutoGeneratedEvents();
      for (final companion in companions) {
        await _db.insertStockEvent(companion);
      }
    });

    return companions.length;
  }

  DateTime? _tryParseDate(String dateStr) {
    try {
      return _dateFormat.parse(dateStr);
    } catch (e) {
      AppLogger.debug('EventRepository', '日期解析失敗: "$dateStr"');
      return null;
    }
  }
}
