import 'package:drift/drift.dart';
import 'package:intl/intl.dart';

import 'package:afterclose/core/utils/logger.dart';
import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/data/remote/twse_client.dart';
import 'package:afterclose/domain/repositories/event_repository.dart';

/// 事件日曆 Repository
///
/// 管理行事曆事件，包括使用者自訂事件與系統自動產生的除權息事件。
class EventRepository implements IEventRepository {
  EventRepository({required AppDatabase database, TwseClient? twseClient})
    : _db = database,
      _twseClient = twseClient;

  final AppDatabase _db;

  /// 停券預告同步用；null 時 [syncShortSuspensionEvents] 直接回 0（測試便利）
  final TwseClient? _twseClient;

  static final _dateFormat = DateFormat('yyyy-MM-dd');

  // ==================================================
  // 事件查詢
  // ==================================================

  /// 取得指定日期範圍內的事件
  @override
  Future<List<StockEventEntry>> getEventsInRange(
    DateTime start,
    DateTime end, {
    List<String>? symbols,
  }) {
    return _db.getEventsInRange(start, end, symbols: symbols);
  }

  // ==================================================
  // 事件操作
  // ==================================================

  /// 新增自訂事件
  @override
  Future<int> addCustomEvent({
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) {
    return _db.insertStockEvent(
      StockEventCompanion.insert(
        symbol: Value(symbol),
        eventType: 'CUSTOM',
        eventDate: eventDate,
        title: title,
        description: Value(description),
      ),
    );
  }

  /// 更新自訂事件
  @override
  Future<void> updateCustomEvent({
    required int id,
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) {
    return _db.updateStockEvent(
      id,
      StockEventCompanion(
        symbol: Value(symbol),
        eventDate: Value(eventDate),
        title: Value(title),
        description: Value(description),
      ),
    );
  }

  /// 刪除事件
  @override
  Future<void> deleteEvent(int id) {
    return _db.deleteStockEvent(id);
  }

  // ==================================================
  // 除權息日同步
  // ==================================================

  /// 從 DividendHistory 同步除權息事件
  ///
  /// 流程：
  /// 1. 取得自選股 + 持倉股的 symbol
  /// 2. 從 DividendHistory 取得有除權息日期的紀錄，收集所有待插入事件
  /// 3. 在單一交易中：刪除舊的自動事件 → 批次插入新事件
  @override
  Future<({int exDividend, int exRights, int total})>
  syncDividendEvents() async {
    // 1. 取得所有相關 symbol（自選股 + 持倉股）
    final watchlistEntries = await _db.getWatchlist();
    final portfolioPositions = await _db.getPortfolioPositions();

    final symbols = <String>{
      ...watchlistEntries.map((e) => e.symbol),
      ...portfolioPositions.map((e) => e.symbol),
    };

    if (symbols.isEmpty) return (exDividend: 0, exRights: 0, total: 0);

    // 2. 收集所有待插入的事件（在交易外讀取）。
    // 改用 batch DAO 取代 per-symbol N+1（過去 N=watchlist+portfolio 約
    // 數十次 round-trip，現在 1 次 SELECT WHERE symbol IN (...) 即可）。
    final dividendsBySymbol = await _db.getDividendHistoryBatch(
      symbols.toList(),
    );
    final companions = <StockEventCompanion>[];
    for (final symbol in symbols) {
      final dividends = dividendsBySymbol[symbol] ?? const [];

      for (final div in dividends) {
        // 除息日
        if (div.exDividendDate != null && div.exDividendDate!.isNotEmpty) {
          final date = _tryParseDate(div.exDividendDate!);
          if (date != null) {
            companions.add(
              StockEventCompanion.insert(
                symbol: Value(symbol),
                eventType: 'EX_DIVIDEND',
                eventDate: date,
                title: '$symbol 除息',
                description: Value(
                  '現金股利 ${div.cashDividend.toStringAsFixed(2)} 元',
                ),
                isAutoGenerated: const Value(true),
              ),
            );
          }
        }

        // 除權日
        if (div.exRightsDate != null && div.exRightsDate!.isNotEmpty) {
          final date = _tryParseDate(div.exRightsDate!);
          if (date != null) {
            companions.add(
              StockEventCompanion.insert(
                symbol: Value(symbol),
                eventType: 'EX_RIGHTS',
                eventDate: date,
                title: '$symbol 除權',
                description: Value(
                  '股票股利 ${div.stockDividend.toStringAsFixed(2)} 元',
                ),
                isAutoGenerated: const Value(true),
              ),
            );
          }
        }
      }
    }

    // 3. 在單一交易中刪除舊的除權息事件並批次插入新事件
    //    只刪除 EX_DIVIDEND + EX_RIGHTS 類型，不影響 SHAREHOLDER_MEETING 等其他自動事件
    await _db.transaction(() async {
      await _db.deleteAutoGeneratedEventsByTypes(const [
        'EX_DIVIDEND',
        'EX_RIGHTS',
      ]);
      for (final companion in companions) {
        await _db.insertStockEvent(companion);
      }
    });

    final exDividendCount = companions
        .where((c) => c.eventType.value == 'EX_DIVIDEND')
        .length;
    final exRightsCount = companions
        .where((c) => c.eventType.value == 'EX_RIGHTS')
        .length;
    return (
      exDividend: exDividendCount,
      exRights: exRightsCount,
      total: companions.length,
    );
  }

  // ==================================================
  // 處置出關日同步
  // ==================================================

  /// 從 active DISPOSAL 警示產生「處置出關」事件。
  ///
  /// v3 交易系統把處置股踢出可交易宇宙，出關日＝重新可交易的日子；
  /// 事件日取 `disposal_end_date`（處置最後一日），標題註明次日恢復。
  /// 與除權息同步同模式：delete-by-type 後重建，冪等。
  @override
  Future<int> syncDisposalEndEvents() async {
    final disposals = await _db.getActiveWarningsByType('DISPOSAL');
    final companions = <StockEventCompanion>[];
    for (final w in disposals) {
      final end = w.disposalEndDate;
      if (end == null) continue;
      companions.add(
        StockEventCompanion.insert(
          symbol: Value(w.symbol),
          eventType: 'DISPOSAL_END',
          eventDate: end,
          title: '${w.symbol} 處置結束',
          description: const Value('處置期滿，次一交易日恢復一般交易'),
          isAutoGenerated: const Value(true),
        ),
      );
    }

    await _db.transaction(() async {
      await _db.deleteAutoGeneratedEventsByTypes(const ['DISPOSAL_END']);
      for (final companion in companions) {
        await _db.insertStockEvent(companion);
      }
    });
    return companions.length;
  }

  // ==================================================
  // 停券預告同步
  // ==================================================

  /// 從 TWSE 停資停券預告（BFI84U）產生自選/持倉股的停券事件。
  ///
  /// 停券起日前的回補賣壓與軋空是短線催化劑；事件日取停券起日，
  /// 描述帶原因與迄日。與其他自動事件同模式：delete-by-type 後重建。
  @override
  Future<int> syncShortSuspensionEvents() async {
    final client = _twseClient;
    if (client == null) return 0;

    final watchlistEntries = await _db.getWatchlist();
    final portfolioPositions = await _db.getPortfolioPositions();
    final symbols = <String>{
      ...watchlistEntries.map((e) => e.symbol),
      ...portfolioPositions.map((e) => e.symbol),
    };

    final rows = await client.getShortSellingSuspensions();
    final companions = <StockEventCompanion>[];
    for (final row in rows) {
      if (!symbols.contains(row.code)) continue;
      final start = rocDateToDateTime(row.startDate);
      if (start == null) continue;
      final end = rocDateToDateTime(row.endDate);
      final endText = end == null ? '' : '，至 ${_dateFormat.format(end)} 恢復';
      companions.add(
        StockEventCompanion.insert(
          symbol: Value(row.code),
          eventType: 'SHORT_SUSPENSION',
          eventDate: start,
          title: '${row.code} 停券起始',
          description: Value('原因：${row.reason}$endText'),
          isAutoGenerated: const Value(true),
        ),
      );
    }

    await _db.transaction(() async {
      await _db.deleteAutoGeneratedEventsByTypes(const ['SHORT_SUSPENSION']);
      for (final companion in companions) {
        await _db.insertStockEvent(companion);
      }
    });
    return companions.length;
  }

  // ==================================================
  // 法說會同步（自重大訊息公告抽取）
  // ==================================================

  /// 從當日重大訊息抽自選∪持倉股的法說會，寫入 EARNINGS 自動事件。
  ///
  /// 事件日＝「說明」內結構化欄位的**開會日**（非公告日）。t187ap04_L
  /// 是每日檔，公告只出現一次 → **累積式**寫入（先比對既有事件的
  /// (symbol, 日) 去重），不可用 delete-by-type 重建（會抹掉往日累積）。
  ///
  /// ⚠️ 若未來新增「財報公布」等第二個 EARNINGS producer：本方法的
  /// (symbol, 日) 去重會讀到**兩個 producer 的事件互相壓制**（同日的
  /// 法說會與財報被誤判重複）——屆時需以 title/來源子欄位區分，並考慮
  /// prune 已過期的 auto EARNINGS（目前無人清理、全史累積）。
  @override
  Future<int> syncInvestorConferenceEvents() async {
    final client = _twseClient;
    if (client == null) return 0;

    final watchlistEntries = await _db.getWatchlist();
    final portfolioPositions = await _db.getPortfolioPositions();
    final symbols = <String>{
      ...watchlistEntries.map((e) => e.symbol),
      ...portfolioPositions.map((e) => e.symbol),
    };
    if (symbols.isEmpty) return 0;

    final rows = await client.getMaterialInformation();
    final existing = await _db.getAutoGeneratedEventsByType('EARNINGS');
    final existingKeys = {
      for (final e in existing)
        '${e.symbol}_${e.eventDate.year}-${e.eventDate.month}-${e.eventDate.day}',
    };

    var inserted = 0;
    for (final info in rows) {
      if (!symbols.contains(info.code)) continue;
      if (!info.isInvestorConference) continue;
      final date = info.conferenceDate;
      if (date == null) continue;
      final key = '${info.code}_${date.year}-${date.month}-${date.day}';
      if (existingKeys.contains(key)) continue;
      existingKeys.add(key);
      await _db.insertStockEvent(
        StockEventCompanion.insert(
          symbol: Value(info.code),
          eventType: 'EARNINGS',
          eventDate: date,
          title: '${info.code} 法說會',
          description: Value(info.subject),
          isAutoGenerated: const Value(true),
        ),
      );
      inserted++;
    }
    return inserted;
  }

  DateTime? _tryParseDate(String dateStr) {
    try {
      return _dateFormat.parse(dateStr);
    } catch (e) {
      AppLogger.debug('EventRepository', '日期解析失敗: "$dateStr"');
      return null;
    }
  }
}
