include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "lib/generated/**"
  errors:
    invalid_annotation_target: ignore
    # Downgrade const hints to info level (won't fail CI)
    prefer_const_constructors: info
    prefer_const_declarations: info

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    cancel_subscriptions: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
