import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/presentation/providers/event_calendar_provider.dart';
import 'package:afterclose/presentation/screens/calendar/event_calendar_screen.dart';

import '../../../helpers/provider_test_helpers.dart';
import '../../../helpers/widget_test_helpers.dart';

// =============================================================================
// Fake Notifier
// =============================================================================

class FakeEventCalendarNotifier extends EventCalendarNotifier {
  EventCalendarState initialState = const EventCalendarState();

  @override
  EventCalendarState build() => initialState;

  @override
  Future<void> init() async {}

  @override
  Future<void> loadMonthEvents(DateTime month) async {}

  @override
  void selectDate(DateTime date) {}

  @override
  Future<void> setFilter(CalendarFilter filter) async {}

  @override
  Future<void> addEvent({
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) async {}

  @override
  Future<void> deleteEvent(int id) async {}

  @override
  Future<int> syncDividendEvents() async => 0;
}

// =============================================================================
// Tests
// =============================================================================

void main() {
  setUpAll(() async {
    await setupTestLocalization();
  });

  void widenViewport(WidgetTester tester) {
    tester.view.physicalSize = const Size(5000, 8000);
    addTearDown(() => tester.view.resetPhysicalSize());
  }

  Widget buildTestWidget({
    EventCalendarState? calendarState,
    Brightness brightness = Brightness.light,
  }) {
    return buildProviderTestApp(
      const EventCalendarScreen(),
      overrides: [
        eventCalendarProvider.overrideWith(() {
          final n = FakeEventCalendarNotifier();
          n.initialState = calendarState ?? const EventCalendarState();
          return n;
        }),
      ],
      brightness: brightness,
    );
  }

  StockEventEntry createEvent({
    int id = 1,
    required String symbol,
    String eventType = 'EX_DIVIDEND',
    String title = 'Test Event',
  }) {
    return StockEventEntry(
      id: id,
      symbol: symbol,
      eventDate: DateTime(2026, 2, 20),
      eventType: eventType,
      title: title,
      isAutoGenerated: false,
      createdAt: DateTime(2026, 2, 1),
    );
  }

  group('EventCalendarScreen', () {
    testWidgets('shows AppBar with title', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(AppBar), findsOneWidget);
    });

    testWidgets('shows filter icon', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.filter_list), findsOneWidget);
    });

    testWidgets('shows loading indicator', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: const EventCalendarState(isLoading: true),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
    });

    testWidgets('shows empty state when no events for selected day', (
      tester,
    ) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.event_busy), findsOneWidget);
    });

    testWidgets('shows events for selected day', (tester) async {
      widenViewport(tester);
      final events = [
        createEvent(id: 1, symbol: '2330', title: 'TSMC Dividend'),
        createEvent(
          id: 2,
          symbol: '2317',
          eventType: 'EARNINGS',
          title: 'Hon Hai Earnings',
        ),
      ];
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
            selectedDayEvents: events,
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.text('TSMC Dividend'), findsOneWidget);
      expect(find.text('Hon Hai Earnings'), findsOneWidget);
    });

    testWidgets('shows FAB for adding event', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(FloatingActionButton), findsOneWidget);
      expect(find.byIcon(Icons.add), findsOneWidget);
    });

    testWidgets('shows sync icon', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.sync), findsOneWidget);
    });

    testWidgets('shows error state', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: const EventCalendarState(error: 'DB error'),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      // Error should be displayed
      expect(find.byType(EventCalendarScreen), findsOneWidget);
    });

    testWidgets('renders in dark mode', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget(brightness: Brightness.dark));
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(EventCalendarScreen), findsOneWidget);
    });
  });
}
