import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:table_calendar/table_calendar.dart';

import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/presentation/providers/event_calendar_provider.dart';
import 'package:afterclose/presentation/screens/calendar/event_calendar_screen.dart';

import '../../../helpers/provider_test_helpers.dart';
import '../../../helpers/widget_test_helpers.dart';

// ==========================================
// Fake Notifier
// ==========================================

class FakeEventCalendarNotifier extends EventCalendarNotifier {
  EventCalendarState initialState = EventCalendarState();

  @override
  EventCalendarState build() => initialState;

  @override
  Future<void> init() async {}

  @override
  Future<bool> loadMonthEvents(DateTime month) async => true;

  @override
  void selectDate(DateTime date) {}

  @override
  Future<void> setFilter(CalendarFilter filter) async {}

  @override
  Future<void> addEvent({
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) async {}

  @override
  Future<void> deleteEvent(int id) async {}

  @override
  Future<({int exDividend, int exRights, int total})>
  syncDividendEvents() async => (exDividend: 0, exRights: 0, total: 0);

  @override
  void toggleEventType(EventType type) {}
}

// ==========================================
// Tests
// ==========================================

void main() {
  setUpAll(() async {
    await setupTestLocalization();
  });

  void widenViewport(WidgetTester tester) {
    tester.view.physicalSize = const Size(5000, 8000);
    addTearDown(() => tester.view.resetPhysicalSize());
  }

  Widget buildTestWidget({
    EventCalendarState? calendarState,
    Brightness brightness = Brightness.light,
  }) {
    return buildProviderTestApp(
      const EventCalendarScreen(),
      overrides: [
        eventCalendarProvider.overrideWith(() {
          final n = FakeEventCalendarNotifier();
          n.initialState = calendarState ?? EventCalendarState();
          return n;
        }),
      ],
      brightness: brightness,
    );
  }

  StockEventEntry createEvent({
    int id = 1,
    required String symbol,
    String eventType = 'EX_DIVIDEND',
    String title = 'Test Event',
  }) {
    return StockEventEntry(
      id: id,
      symbol: symbol,
      eventDate: DateTime(2026, 2, 20),
      eventType: eventType,
      title: title,
      isAutoGenerated: false,
      createdAt: DateTime(2026, 2, 1),
    );
  }

  group('EventCalendarScreen', () {
    testWidgets('shows AppBar with title', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(AppBar), findsOneWidget);
    });

    testWidgets('shows filter icon', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.filter_list), findsOneWidget);
    });

    testWidgets('shows loading indicator', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(calendarState: EventCalendarState(isLoading: true)),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
    });

    testWidgets('shows empty state when no events for selected day', (
      tester,
    ) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.event_busy), findsOneWidget);
    });

    testWidgets('shows events for selected day', (tester) async {
      widenViewport(tester);
      final events = [
        createEvent(id: 1, symbol: '2330', title: 'TSMC Dividend'),
        createEvent(
          id: 2,
          symbol: '2317',
          eventType: 'EARNINGS',
          title: 'Hon Hai Earnings',
        ),
      ];
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
            selectedDayEvents: events,
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.text('TSMC Dividend'), findsOneWidget);
      expect(find.text('Hon Hai Earnings'), findsOneWidget);
    });

    testWidgets('shows FAB for adding event', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(FloatingActionButton), findsOneWidget);
      expect(find.byIcon(Icons.add), findsOneWidget);
    });

    testWidgets('shows sync icon', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.sync), findsOneWidget);
    });

    testWidgets('format button uses localized labels instead of package '
        'English defaults', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      // 套件預設 availableCalendarFormats 是英文（'2 weeks' 等）；本 app 需
      // 傳入 i18n key（測試環境 .tr() 回傳 key 本身）。formatButtonShowsNext
      // 預設 true → 月檢視下按鈕顯示「下一個」格式（twoWeeks）的 label。
      expect(find.text('2 weeks'), findsNothing);
      expect(find.text('calendar.formatTwoWeeks'), findsOneWidget);
    });

    testWidgets('wide viewport: two panes fill window width adaptively', (
      tester,
    ) async {
      widenViewport(tester); // 5000x8000 physical / dpr 3 ≈ 1666 邏輯寬
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      // 自適應：雙欄吃滿視窗（僅留 16dp 外框），不得置中留大幅死空白
      // （2026-07-24 使用者回饋：左右兩側空白很大）
      final calendarLeft = tester
          .getTopLeft(find.byType(TableCalendar<StockEventEntry>))
          .dx;
      expect(
        calendarLeft,
        lessThan(100),
        reason: '左欄應貼近視窗左緣（外框 padding 內），非置中留白',
      );
    });

    testWidgets('wide viewport uses two-pane layout (calendar left, '
        'upcoming+day events right)', (tester) async {
      widenViewport(tester); // 邏輯寬 ~1666 ≥ Breakpoints.tablet → 雙欄
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
            upcomingEvents: [createEvent(id: 9, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final calendarRight = tester
          .getBottomRight(find.byType(TableCalendar<StockEventEntry>))
          .dx;
      final upcomingLeft = tester
          .getTopLeft(find.text('calendar.upcomingTitle'))
          .dx;
      expect(
        upcomingLeft,
        greaterThan(calendarRight),
        reason: '寬視窗下「未來14天」應在月曆右側欄，而非上方',
      );
    });

    testWidgets('narrow viewport keeps single-column layout '
        '(upcoming above calendar)', (tester) async {
      // 邏輯 560x800（<1024 仍屬單欄）。不用 400：測試環境 .tr() 會把
      // 'calendar.formatTwoWeeks' key 原樣渲染進 format 按鈕，400 寬會被
      // 長 key 撐爆 header Row（僅測試 artifact，真翻譯為「兩週」）。
      tester.view.physicalSize = const Size(1680, 2400);
      addTearDown(() => tester.view.resetPhysicalSize());
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            upcomingEvents: [createEvent(id: 9, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final upcomingBottom = tester
          .getBottomLeft(find.text('calendar.upcomingTitle'))
          .dy;
      final calendarTop = tester
          .getTopLeft(find.byType(TableCalendar<StockEventEntry>))
          .dy;
      expect(
        upcomingBottom,
        lessThan(calendarTop),
        reason: '窄視窗維持單欄：「未來14天」在月曆上方',
      );
    });

    testWidgets('filter chips: 兩態皆中性、類型色只留色點 avatar', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedEventTypes: EventType.values.toSet()
              ..remove(EventType.exDividend),
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final chips = tester
          .widgetList<FilterChip>(find.byType(FilterChip))
          .toList();
      expect(chips, hasLength(EventType.values.length));

      // 預設五類全選會恆常呈彩虹，故兩態 label 皆不得著類型色、
      // avatar 一律為小色點（識別靠色點、選取靠底色＋勾勾）
      for (final chip in chips) {
        expect(
          chip.labelStyle?.color,
          isNull,
          reason: 'chip label 不著類型色（選中與否皆同）',
        );
        expect(
          chip.avatar,
          isNot(isA<Icon>()),
          reason: 'avatar 一律為色點而非彩色 icon',
        );
      }
      expect(
        chips.where((c) => !c.selected),
        hasLength(1),
        reason: 'exDividend 應為唯一未選中',
      );
    });

    testWidgets('shows error state', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(calendarState: EventCalendarState(error: 'DB error')),
      );
      await tester.pump(const Duration(seconds: 1));

      // Error should be displayed
      expect(find.byType(EventCalendarScreen), findsOneWidget);
    });
  });
}
