import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/presentation/providers/event_calendar_provider.dart';
import 'package:afterclose/presentation/screens/calendar/widgets/event_list_tile.dart';

import '../../../../helpers/widget_test_helpers.dart';

void main() {
  setUpAll(() async {
    await setupTestLocalization();
  });

  StockEventEntry createEvent({
    int id = 1,
    String? symbol = '2330',
    String eventType = 'EX_DIVIDEND',
    String title = '除息',
    String? description,
    bool isAutoGenerated = false,
  }) {
    return StockEventEntry(
      id: id,
      symbol: symbol,
      eventType: eventType,
      eventDate: DateTime(2026, 3, 15),
      title: title,
      description: description,
      isAutoGenerated: isAutoGenerated,
      createdAt: DateTime(2026, 2, 1),
    );
  }

  group('eventTypeColor', () {
    test('exDividend returns red', () {
      expect(eventTypeColor(EventType.exDividend), Colors.red);
    });

    test('exRights returns orange', () {
      expect(eventTypeColor(EventType.exRights), Colors.orange);
    });

    test('earnings returns green', () {
      expect(eventTypeColor(EventType.earnings), Colors.green);
    });

    test('custom returns blue', () {
      expect(eventTypeColor(EventType.custom), Colors.blue);
    });
  });

  group('EventListTile', () {
    testWidgets('displays event title', (tester) async {
      await tester.pumpWidget(
        buildTestApp(EventListTile(event: createEvent(title: '台積電除息'))),
      );

      expect(find.text('台積電除息'), findsOneWidget);
    });

    testWidgets('displays description when provided', (tester) async {
      await tester.pumpWidget(
        buildTestApp(
          EventListTile(
            event: createEvent(title: '除息', description: '現金股利 3.0 元'),
          ),
        ),
      );

      expect(find.text('現金股利 3.0 元'), findsOneWidget);
    });

    testWidgets('hides description when null', (tester) async {
      await tester.pumpWidget(
        buildTestApp(EventListTile(event: createEvent(description: null))),
      );

      // Only title and type label should exist, no description text
      expect(find.byType(EventListTile), findsOneWidget);
    });

    testWidgets('shows auto_awesome icon for auto-generated events', (
      tester,
    ) async {
      await tester.pumpWidget(
        buildTestApp(EventListTile(event: createEvent(isAutoGenerated: true))),
      );

      expect(find.byIcon(Icons.auto_awesome), findsOneWidget);
    });

    testWidgets('hides auto_awesome icon for manual events', (tester) async {
      await tester.pumpWidget(
        buildTestApp(EventListTile(event: createEvent(isAutoGenerated: false))),
      );

      expect(find.byIcon(Icons.auto_awesome), findsNothing);
    });

    testWidgets('shows payments icon for exDividend type', (tester) async {
      await tester.pumpWidget(
        buildTestApp(
          EventListTile(event: createEvent(eventType: 'EX_DIVIDEND')),
        ),
      );

      expect(find.byIcon(Icons.payments_outlined), findsOneWidget);
    });

    testWidgets('shows article icon for earnings type', (tester) async {
      await tester.pumpWidget(
        buildTestApp(EventListTile(event: createEvent(eventType: 'EARNINGS'))),
      );

      expect(find.byIcon(Icons.article_outlined), findsOneWidget);
    });

    testWidgets('renders in dark mode', (tester) async {
      await tester.pumpWidget(
        buildTestApp(
          EventListTile(event: createEvent()),
          brightness: Brightness.dark,
        ),
      );

      expect(find.byType(EventListTile), findsOneWidget);
    });
  });
}
