import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/data/remote/tpex_client.dart';
import 'package:afterclose/data/remote/twse_client.dart';
import 'package:afterclose/domain/services/update/dividend_syncer.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockAppDatabase extends Mock implements AppDatabase {
  @override
  Future<T> transaction<T>(Future<T> Function() action, {bool? requireNew}) {
    return action();
  }
}

class MockTwseClient extends Mock implements TwseClient {}

class MockTpexClient extends Mock implements TpexClient {}

class _FakeStockEventCompanion extends Fake implements StockEventCompanion {}

StockMasterEntry _stock(String symbol, String market) => StockMasterEntry(
  symbol: symbol,
  name: symbol,
  market: market,
  industry: '測試',
  isActive: true,
  updatedAt: DateTime(2026, 7, 17),
);

void main() {
  setUpAll(() {
    registerFallbackValue(<String>[]);
    registerFallbackValue(<DividendHistoryCompanion>[]);
    registerFallbackValue(_FakeStockEventCompanion());
  });

  late MockAppDatabase db;
  late MockTwseClient twse;
  late MockTpexClient tpex;
  late DividendSyncer syncer;

  setUp(() {
    db = MockAppDatabase();
    twse = MockTwseClient();
    tpex = MockTpexClient();
    syncer = DividendSyncer(database: db, twseClient: twse, tpexClient: tpex);

    // 上市 2330、上櫃 5483 皆為已知股票
    when(
      () => db.getAllActiveStocks(),
    ).thenAnswer((_) async => [_stock('2330', 'TWSE'), _stock('5483', 'TPEX')]);
    when(() => db.insertDividendData(any())).thenAnswer((_) async {});
    when(
      () => db.deleteAutoGeneratedEventsByTypes(any()),
    ).thenAnswer((_) async {});
    when(() => db.insertStockEvent(any())).thenAnswer((_) async => 1);
  });

  group('DividendSyncer 股東會破壞性寫入守衛', () {
    test('TWSE 失敗、TPEX 成功時不得全市場刪除股東會事件（保留 TWSE 既有資料）', () async {
      // TWSE 已宣告股利（含股東會）取得失敗（網路瞬斷 → 被 catch，非 rethrow 型）
      when(
        () => twse.getDeclaredDividends(),
      ).thenThrow(Exception('twse transient boom'));
      // TPEX 股利空、股東會成功回一筆（上櫃 5483）
      when(
        () => tpex.getDeclaredDividends(),
      ).thenAnswer((_) async => <TpexDeclaredDividend>[]);
      when(() => tpex.getShareholderMeetings()).thenAnswer(
        (_) async => [
          TpexShareholderMeeting(
            symbol: '5483',
            companyName: '中美晶',
            meetingType: '股東常會',
            meetingDate: DateTime(2026, 8, 20),
            hasBoardElection: false,
            hasEVoting: true,
          ),
        ],
      );

      final result = await syncer.sync();

      // 核心斷言：TWSE 這個股東會來源失敗 → 不可執行全市場無差別刪除，
      // 否則會清掉 TWSE 上一輪正確寫入的上市公司股東會事件且無法補回。
      verifyNever(() => db.deleteAutoGeneratedEventsByTypes(any()));
      // 略過重建 → 不做任何部分插入
      verifyNever(() => db.insertStockEvent(any()));
      // 失敗有記錄
      expect(result.hasErrors, isTrue);
    });

    test('兩來源皆成功時仍照常重建股東會事件（既有行為保留）', () async {
      when(() => twse.getDeclaredDividends()).thenAnswer(
        (_) async => [
          TwseDeclaredDividend(
            symbol: '2330',
            companyName: '台積電',
            dividendYear: 2026,
            cashDividend: 4.0,
            stockDividend: 0.0,
            shareholderMeetingDate: DateTime(2026, 8, 15),
          ),
        ],
      );
      when(
        () => tpex.getDeclaredDividends(),
      ).thenAnswer((_) async => <TpexDeclaredDividend>[]);
      when(() => tpex.getShareholderMeetings()).thenAnswer(
        (_) async => [
          TpexShareholderMeeting(
            symbol: '5483',
            companyName: '中美晶',
            meetingType: '股東常會',
            meetingDate: DateTime(2026, 8, 20),
            hasBoardElection: false,
            hasEVoting: true,
          ),
        ],
      );

      final result = await syncer.sync();

      // 兩來源皆完整 → 全市場刪除 + 重建（各一筆：2330、5483）
      verify(
        () =>
            db.deleteAutoGeneratedEventsByTypes(const ['SHAREHOLDER_MEETING']),
      ).called(1);
      verify(() => db.insertStockEvent(any())).called(2);
      expect(result.meetingEventsCreated, 2);
    });
  });
}
