import 'package:afterclose/data/database/app_database.dart';
import 'package:afterclose/data/remote/twse_client.dart';
import 'package:afterclose/data/repositories/event_repository.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockAppDatabase extends Mock implements AppDatabase {
  @override
  Future<T> transaction<T>(Future<T> Function() action, {bool? requireNew}) {
    return action();
  }
}

class FakeStockEventCompanion extends Fake implements StockEventCompanion {}

class MockTwseClient extends Mock implements TwseClient {}

void main() {
  setUpAll(() {
    registerFallbackValue(FakeStockEventCompanion());
  });

  late MockAppDatabase mockDb;
  late EventRepository repository;

  setUp(() {
    mockDb = MockAppDatabase();
    repository = EventRepository(database: mockDb);
  });

  // ==========================================
  // 事件查詢
  // ==========================================
  group('getEventsInRange', () {
    test('delegates to database', () async {
      final start = DateTime(2025, 1, 1);
      final end = DateTime(2025, 1, 31);
      final events = [
        StockEventEntry(
          id: 1,
          symbol: '2330',
          eventType: 'EX_DIVIDEND',
          eventDate: DateTime(2025, 1, 15),
          title: '2330 除息',
          isAutoGenerated: true,
          createdAt: DateTime(2025, 1, 1),
        ),
      ];

      when(
        () =>
            mockDb.getEventsInRange(start, end, symbols: any(named: 'symbols')),
      ).thenAnswer((_) async => events);

      final result = await repository.getEventsInRange(start, end);

      expect(result, equals(events));
      verify(
        () =>
            mockDb.getEventsInRange(start, end, symbols: any(named: 'symbols')),
      ).called(1);
    });
  });

  // ==========================================
  // 事件操作
  // ==========================================
  group('addCustomEvent', () {
    test('inserts CUSTOM event with correct fields', () async {
      when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 42);

      final eventDate = DateTime(2025, 3, 15);
      final result = await repository.addCustomEvent(
        symbol: '2330',
        eventDate: eventDate,
        title: '法說會',
        description: '第一季法說會',
      );

      expect(result, equals(42));

      final captured =
          verify(() => mockDb.insertStockEvent(captureAny())).captured.single
              as StockEventCompanion;
      expect(captured.eventType.value, equals('CUSTOM'));
      expect(captured.eventDate.value, equals(eventDate));
      expect(captured.title.value, equals('法說會'));
      expect(captured.description.value, equals('第一季法說會'));
      expect(captured.symbol.value, equals('2330'));
    });

    test('allows null symbol for personal memo events', () async {
      when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 43);

      await repository.addCustomEvent(
        eventDate: DateTime(2025, 3, 15),
        title: '個人備忘',
      );

      final captured =
          verify(() => mockDb.insertStockEvent(captureAny())).captured.single
              as StockEventCompanion;
      // addCustomEvent passes Value(symbol) where symbol is null
      expect(captured.symbol.value, isNull);
    });
  });

  group('deleteEvent', () {
    test('delegates to database', () async {
      when(() => mockDb.deleteStockEvent(42)).thenAnswer((_) async {});

      await repository.deleteEvent(42);

      verify(() => mockDb.deleteStockEvent(42)).called(1);
    });
  });

  // ==========================================
  // 除權息日同步
  // ==========================================
  group('rocDateToDateTime', () {
    test('民國年字串轉西元 DateTime', () {
      expect(rocDateToDateTime('1150730'), DateTime(2026, 7, 30));
      expect(rocDateToDateTime('1150101'), DateTime(2026, 1, 1));
      expect(rocDateToDateTime('bad'), isNull);
      expect(rocDateToDateTime(''), isNull);
      // 2/30 這種不存在的日期不得溢位進位成 3/2
      expect(rocDateToDateTime('1150230'), isNull);
    });
  });

  group('syncShortSuspensionEvents', () {
    late MockTwseClient mockClient;

    setUp(() {
      mockClient = MockTwseClient();
      repository = EventRepository(database: mockDb, twseClient: mockClient);
    });

    test('停券預告過濾到自選/持倉、寫入事件並回傳筆數', () async {
      when(() => mockDb.getWatchlist()).thenAnswer(
        (_) async => [
          WatchlistEntry(symbol: '3231', createdAt: DateTime(2026, 1, 1)),
        ],
      );
      when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);
      when(() => mockClient.getShortSellingSuspensions()).thenAnswer(
        (_) async => [
          const TwseShortSuspension(
            code: '3231',
            name: '緯創',
            startDate: '1150730',
            endDate: '1150804',
            reason: '股東會',
          ),
          const TwseShortSuspension(
            code: '9999',
            name: '非自選',
            startDate: '1150730',
            endDate: '1150804',
            reason: '除息',
          ),
        ],
      );
      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});
      when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 1);

      final count = await repository.syncShortSuspensionEvents();

      expect(count, 1);
      verify(
        () => mockDb.deleteAutoGeneratedEventsByTypes(['SHORT_SUSPENSION']),
      ).called(1);
      final captured = verify(
        () => mockDb.insertStockEvent(captureAny()),
      ).captured.cast<StockEventCompanion>();
      expect(captured, hasLength(1));
      expect(captured.first.symbol.value, '3231');
      expect(captured.first.eventType.value, 'SHORT_SUSPENSION');
      expect(captured.first.eventDate.value, DateTime(2026, 7, 30));
      expect(captured.first.title.value, contains('停券'));
      expect(captured.first.description.value, contains('股東會'));
      expect(captured.first.isAutoGenerated.value, isTrue);
    });

    test('未注入 client 時回 0 不打 API', () async {
      repository = EventRepository(database: mockDb);
      final count = await repository.syncShortSuspensionEvents();
      expect(count, 0);
    });
  });

  group('syncDisposalEndEvents', () {
    TradingWarningEntry warning({
      required String symbol,
      DateTime? endDate,
      bool isActive = true,
    }) {
      return TradingWarningEntry(
        symbol: symbol,
        date: DateTime(2026, 7, 1),
        warningType: 'DISPOSAL',
        isActive: isActive,
        disposalEndDate: endDate,
      );
    }

    test('從 active DISPOSAL 產生出關事件（先刪舊、再插入、回傳筆數）', () async {
      when(() => mockDb.getActiveWarningsByType('DISPOSAL')).thenAnswer(
        (_) async => [
          warning(symbol: '3260', endDate: DateTime(2026, 8, 5)),
          warning(symbol: '4939', endDate: DateTime(2026, 8, 12)),
        ],
      );
      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});
      when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 1);

      final count = await repository.syncDisposalEndEvents();

      expect(count, 2);
      verify(
        () => mockDb.deleteAutoGeneratedEventsByTypes(['DISPOSAL_END']),
      ).called(1);
      final captured = verify(
        () => mockDb.insertStockEvent(captureAny()),
      ).captured.cast<StockEventCompanion>();
      expect(captured, hasLength(2));
      expect(captured.first.eventType.value, 'DISPOSAL_END');
      expect(captured.first.symbol.value, '3260');
      expect(captured.first.eventDate.value, DateTime(2026, 8, 5));
      expect(captured.first.isAutoGenerated.value, isTrue);
      expect(captured.first.title.value, contains('處置結束'));
    });

    test('無 disposal_end_date 的處置股跳過', () async {
      when(
        () => mockDb.getActiveWarningsByType('DISPOSAL'),
      ).thenAnswer((_) async => [warning(symbol: '3260', endDate: null)]);
      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});

      final count = await repository.syncDisposalEndEvents();

      expect(count, 0);
      verifyNever(() => mockDb.insertStockEvent(any()));
    });
  });

  group('syncDividendEvents', () {
    test('returns 0 when no watchlist or positions', () async {
      when(() => mockDb.getWatchlist()).thenAnswer((_) async => []);
      when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);

      final result = await repository.syncDividendEvents();

      expect(result.total, equals(0));
      expect(result.exDividend, equals(0));
      expect(result.exRights, equals(0));
    });

    test(
      'creates EX_DIVIDEND and EX_RIGHTS events from dividend history',
      () async {
        when(() => mockDb.getWatchlist()).thenAnswer(
          (_) async => [
            WatchlistEntry(symbol: '2330', createdAt: DateTime(2025, 1, 1)),
          ],
        );
        when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);
        when(() => mockDb.getDividendHistoryBatch(any())).thenAnswer(
          (_) async => {
            '2330': [
              const DividendHistoryEntry(
                symbol: '2330',
                year: 2024,
                cashDividend: 3.5,
                stockDividend: 0.5,
                exDividendDate: '2024-07-15',
                exRightsDate: '2024-08-20',
              ),
            ],
          },
        );

        when(
          () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
        ).thenAnswer((_) async {});
        when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 1);

        final result = await repository.syncDividendEvents();

        // 1 exDividendDate + 1 exRightsDate = 2 events
        expect(result.total, equals(2));
        expect(result.exDividend, equals(1));
        expect(result.exRights, equals(1));
        verify(() => mockDb.deleteAutoGeneratedEventsByTypes(any())).called(1);
        verify(() => mockDb.insertStockEvent(any())).called(2);
      },
    );

    test('skips null or empty dividend dates', () async {
      when(() => mockDb.getWatchlist()).thenAnswer(
        (_) async => [
          WatchlistEntry(symbol: '2330', createdAt: DateTime(2025, 1, 1)),
        ],
      );
      when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);
      when(() => mockDb.getDividendHistoryBatch(any())).thenAnswer(
        (_) async => {
          '2330': [
            const DividendHistoryEntry(
              symbol: '2330',
              year: 2024,
              cashDividend: 3.5,
              stockDividend: 0,
              exDividendDate: null,
              exRightsDate: '',
            ),
          ],
        },
      );

      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});

      final result = await repository.syncDividendEvents();

      expect(result.total, equals(0));
      verifyNever(() => mockDb.insertStockEvent(any()));
    });

    test('skips invalid date strings', () async {
      when(() => mockDb.getWatchlist()).thenAnswer(
        (_) async => [
          WatchlistEntry(symbol: '2330', createdAt: DateTime(2025, 1, 1)),
        ],
      );
      when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);
      when(() => mockDb.getDividendHistoryBatch(any())).thenAnswer(
        (_) async => {
          '2330': [
            const DividendHistoryEntry(
              symbol: '2330',
              year: 2024,
              cashDividend: 3.5,
              stockDividend: 0,
              exDividendDate: 'not-a-date',
            ),
          ],
        },
      );

      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});

      final result = await repository.syncDividendEvents();

      expect(result.total, equals(0));
      verifyNever(() => mockDb.insertStockEvent(any()));
    });

    test('deduplicates symbols from watchlist and portfolio', () async {
      when(() => mockDb.getWatchlist()).thenAnswer(
        (_) async => [
          WatchlistEntry(symbol: '2330', createdAt: DateTime(2025, 1, 1)),
        ],
      );
      when(() => mockDb.getPortfolioPositions()).thenAnswer(
        (_) async => [
          PortfolioPositionEntry(
            id: 1,
            symbol: '2330', // same symbol in both
            quantity: 1000,
            avgCost: 500,
            realizedPnl: 0,
            totalDividendReceived: 0,
            createdAt: DateTime(2025, 1, 1),
            updatedAt: DateTime(2025, 1, 1),
          ),
        ],
      );
      when(() => mockDb.getDividendHistoryBatch(any())).thenAnswer(
        (_) async => {
          '2330': [
            const DividendHistoryEntry(
              symbol: '2330',
              year: 2024,
              cashDividend: 3.5,
              stockDividend: 0,
              exDividendDate: '2024-07-15',
            ),
          ],
        },
      );

      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});
      when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 1);

      final result = await repository.syncDividendEvents();

      // Only 1 event (not duplicated for same symbol)
      expect(result.total, equals(1));
      expect(result.exDividend, equals(1));
      expect(result.exRights, equals(0));
      // getDividendHistory called once for '2330', not twice
      verify(() => mockDb.getDividendHistoryBatch(any())).called(1);
    });
  });
}
