import 'package:drift/drift.dart' show Value;
import 'package:flutter_test/flutter_test.dart';

import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/repositories/event_repository.dart';

/// syncInvestorConferenceEvents 累積路徑的真 DB 守門(2026-08-01 複審)。
///
/// ef6f0446 的真 DB 冪等測試只蓋到 insertNewsWithMappings(news_item 層);
/// 法說會事件的「累積式 (symbol, 開會日) 去重」這條更易踩雷的路徑先前
/// 全靠 MockAppDatabase,零真 DB 覆蓋。
///
/// 已知限制(列管,見 syncInvestorConferenceEvents docstring):公告更正/
/// 改期會派生第二筆事件且舊事件永久殘留——公告永久累積意味著舊公告永遠
/// 派生舊日期;盲目 supersede 又會誤殺同公司多場法說會的合法情境。正確
/// 的更正語意需真實 MOPS 更正公告樣本才能設計,樣本到手前不做啟發式。
void main() {
  late AppDatabase db;
  late EventRepository repo;

  Future<void> seedAnnouncement({
    required String id,
    required String symbol,
    required String rocDate, // 例 '115/9/10'
  }) async {
    await db.insertNewsWithMappings(
      [
        NewsItemCompanion.insert(
          id: id,
          source: '重大訊息',
          title: '$symbol 公告本公司受邀參加法人說明會',
          content: Value('召開法人說明會之日期：$rocDate'),
          url: '',
          category: 'announcement',
          publishedAt: DateTime(2026, 7, 24),
        ),
      ],
      [NewsStockMapCompanion.insert(newsId: id, symbol: symbol)],
    );
  }

  setUp(() async {
    db = AppDatabase.forTesting();
    for (final s in ['2330', '9999']) {
      await db.upsertStocks([
        StockMasterCompanion.insert(symbol: s, name: '測試$s', market: 'TWSE'),
      ]);
    }
    await db.addToWatchlist('2330');
    repo = EventRepository(database: db);
  });

  tearDown(() async => db.close());

  test('同一公告重跑冪等:事件不重複', () async {
    await seedAnnouncement(id: 'mops_1', symbol: '2330', rocDate: '115/9/10');

    expect(await repo.syncInvestorConferenceEvents(), 1);
    expect(await repo.syncInvestorConferenceEvents(), 0, reason: '重跑不得重插');

    final events = await db.getAutoGeneratedEventsByType('EARNINGS');
    expect(events, hasLength(1));
    expect(events.single.eventDate, DateTime(2026, 9, 10));
  });

  test('同公司多場法說會(不同開會日)各建一筆——累積式設計的合法分支', () async {
    await seedAnnouncement(id: 'mops_1', symbol: '2330', rocDate: '115/9/10');
    await seedAnnouncement(id: 'mops_2', symbol: '2330', rocDate: '115/11/20');

    await repo.syncInvestorConferenceEvents();

    final events = await db.getAutoGeneratedEventsByType('EARNINGS');
    expect(events, hasLength(2));
  });

  test('非自選∪持倉的公告不建事件', () async {
    await seedAnnouncement(id: 'mops_3', symbol: '9999', rocDate: '115/9/10');

    expect(await repo.syncInvestorConferenceEvents(), 0);
  });
}
