import 'package:drift/drift.dart';

/// 使用者自訂事件 / 系統自動事件 Table
///
/// 事件類型：
/// - EX_DIVIDEND: 除息日（自動從 DividendHistory 匯入）
/// - EX_RIGHTS: 除權日（自動從 DividendHistory 匯入）
/// - EARNINGS: 財報公布日
/// - CUSTOM: 使用者自訂備忘
@DataClassName('StockEventEntry')
@TableIndex(name: 'idx_stock_event_date', columns: {#eventDate})
@TableIndex(name: 'idx_stock_event_symbol', columns: {#symbol})
class StockEvent extends Table {
  /// 自動遞增 ID
  IntColumn get id => integer().autoIncrement()();

  /// 股票代碼（可為空，允許純個人備忘事件）
  TextColumn get symbol => text().nullable()();

  /// 事件類型：EX_DIVIDEND, EX_RIGHTS, EARNINGS, CUSTOM
  TextColumn get eventType => text()();

  /// 事件日期
  DateTimeColumn get eventDate => dateTime()();

  /// 事件標題
  TextColumn get title => text()();

  /// 事件描述/備註
  TextColumn get description => text().nullable()();

  /// 是否為系統自動產生
  BoolColumn get isAutoGenerated =>
      boolean().withDefault(const Constant(false))();

  /// 建立時間
  DateTimeColumn get createdAt =>
      dateTime().withDefault(currentDateAndTime)();
}
