// dart format width=80
// ignore_for_file: type=lint
import 'package:drift/drift.dart' as i0;
import 'package:afterclose/data/database/tables/event_tables.drift.dart' as i1;
import 'package:afterclose/data/database/tables/event_tables.dart' as i2;
import 'package:drift/src/runtime/query_builder/query_builder.dart' as i3;

typedef $$StockEventTableCreateCompanionBuilder =
    i1.StockEventCompanion Function({
      i0.Value<int> id,
      i0.Value<String?> symbol,
      required String eventType,
      required DateTime eventDate,
      required String title,
      i0.Value<String?> description,
      i0.Value<bool> isAutoGenerated,
      i0.Value<DateTime> createdAt,
    });
typedef $$StockEventTableUpdateCompanionBuilder =
    i1.StockEventCompanion Function({
      i0.Value<int> id,
      i0.Value<String?> symbol,
      i0.Value<String> eventType,
      i0.Value<DateTime> eventDate,
      i0.Value<String> title,
      i0.Value<String?> description,
      i0.Value<bool> isAutoGenerated,
      i0.Value<DateTime> createdAt,
    });

class $$StockEventTableFilterComposer
    extends i0.Composer<i0.GeneratedDatabase, i1.$StockEventTable> {
  $$StockEventTableFilterComposer({
    required super.$db,
    required super.$table,
    super.joinBuilder,
    super.$addJoinBuilderToRootComposer,
    super.$removeJoinBuilderFromRootComposer,
  });
  i0.ColumnFilters<int> get id => $composableBuilder(
    column: $table.id,
    builder: (column) => i0.ColumnFilters(column),
  );

  i0.ColumnFilters<String> get symbol => $composableBuilder(
    column: $table.symbol,
    builder: (column) => i0.ColumnFilters(column),
  );

  i0.ColumnFilters<String> get eventType => $composableBuilder(
    column: $table.eventType,
    builder: (column) => i0.ColumnFilters(column),
  );

  i0.ColumnFilters<DateTime> get eventDate => $composableBuilder(
    column: $table.eventDate,
    builder: (column) => i0.ColumnFilters(column),
  );

  i0.ColumnFilters<String> get title => $composableBuilder(
    column: $table.title,
    builder: (column) => i0.ColumnFilters(column),
  );

  i0.ColumnFilters<String> get description => $composableBuilder(
    column: $table.description,
    builder: (column) => i0.ColumnFilters(column),
  );

  i0.ColumnFilters<bool> get isAutoGenerated => $composableBuilder(
    column: $table.isAutoGenerated,
    builder: (column) => i0.ColumnFilters(column),
  );

  i0.ColumnFilters<DateTime> get createdAt => $composableBuilder(
    column: $table.createdAt,
    builder: (column) => i0.ColumnFilters(column),
  );
}

class $$StockEventTableOrderingComposer
    extends i0.Composer<i0.GeneratedDatabase, i1.$StockEventTable> {
  $$StockEventTableOrderingComposer({
    required super.$db,
    required super.$table,
    super.joinBuilder,
    super.$addJoinBuilderToRootComposer,
    super.$removeJoinBuilderFromRootComposer,
  });
  i0.ColumnOrderings<int> get id => $composableBuilder(
    column: $table.id,
    builder: (column) => i0.ColumnOrderings(column),
  );

  i0.ColumnOrderings<String> get symbol => $composableBuilder(
    column: $table.symbol,
    builder: (column) => i0.ColumnOrderings(column),
  );

  i0.ColumnOrderings<String> get eventType => $composableBuilder(
    column: $table.eventType,
    builder: (column) => i0.ColumnOrderings(column),
  );

  i0.ColumnOrderings<DateTime> get eventDate => $composableBuilder(
    column: $table.eventDate,
    builder: (column) => i0.ColumnOrderings(column),
  );

  i0.ColumnOrderings<String> get title => $composableBuilder(
    column: $table.title,
    builder: (column) => i0.ColumnOrderings(column),
  );

  i0.ColumnOrderings<String> get description => $composableBuilder(
    column: $table.description,
    builder: (column) => i0.ColumnOrderings(column),
  );

  i0.ColumnOrderings<bool> get isAutoGenerated => $composableBuilder(
    column: $table.isAutoGenerated,
    builder: (column) => i0.ColumnOrderings(column),
  );

  i0.ColumnOrderings<DateTime> get createdAt => $composableBuilder(
    column: $table.createdAt,
    builder: (column) => i0.ColumnOrderings(column),
  );
}

class $$StockEventTableAnnotationComposer
    extends i0.Composer<i0.GeneratedDatabase, i1.$StockEventTable> {
  $$StockEventTableAnnotationComposer({
    required super.$db,
    required super.$table,
    super.joinBuilder,
    super.$addJoinBuilderToRootComposer,
    super.$removeJoinBuilderFromRootComposer,
  });
  i0.GeneratedColumn<int> get id =>
      $composableBuilder(column: $table.id, builder: (column) => column);

  i0.GeneratedColumn<String> get symbol =>
      $composableBuilder(column: $table.symbol, builder: (column) => column);

  i0.GeneratedColumn<String> get eventType =>
      $composableBuilder(column: $table.eventType, builder: (column) => column);

  i0.GeneratedColumn<DateTime> get eventDate =>
      $composableBuilder(column: $table.eventDate, builder: (column) => column);

  i0.GeneratedColumn<String> get title =>
      $composableBuilder(column: $table.title, builder: (column) => column);

  i0.GeneratedColumn<String> get description => $composableBuilder(
    column: $table.description,
    builder: (column) => column,
  );

  i0.GeneratedColumn<bool> get isAutoGenerated => $composableBuilder(
    column: $table.isAutoGenerated,
    builder: (column) => column,
  );

  i0.GeneratedColumn<DateTime> get createdAt =>
      $composableBuilder(column: $table.createdAt, builder: (column) => column);
}

class $$StockEventTableTableManager
    extends
        i0.RootTableManager<
          i0.GeneratedDatabase,
          i1.$StockEventTable,
          i1.StockEventEntry,
          i1.$$StockEventTableFilterComposer,
          i1.$$StockEventTableOrderingComposer,
          i1.$$StockEventTableAnnotationComposer,
          $$StockEventTableCreateCompanionBuilder,
          $$StockEventTableUpdateCompanionBuilder,
          (
            i1.StockEventEntry,
            i0.BaseReferences<
              i0.GeneratedDatabase,
              i1.$StockEventTable,
              i1.StockEventEntry
            >,
          ),
          i1.StockEventEntry,
          i0.PrefetchHooks Function()
        > {
  $$StockEventTableTableManager(
    i0.GeneratedDatabase db,
    i1.$StockEventTable table,
  ) : super(
        i0.TableManagerState(
          db: db,
          table: table,
          createFilteringComposer: () =>
              i1.$$StockEventTableFilterComposer($db: db, $table: table),
          createOrderingComposer: () =>
              i1.$$StockEventTableOrderingComposer($db: db, $table: table),
          createComputedFieldComposer: () =>
              i1.$$StockEventTableAnnotationComposer($db: db, $table: table),
          updateCompanionCallback:
              ({
                i0.Value<int> id = const i0.Value.absent(),
                i0.Value<String?> symbol = const i0.Value.absent(),
                i0.Value<String> eventType = const i0.Value.absent(),
                i0.Value<DateTime> eventDate = const i0.Value.absent(),
                i0.Value<String> title = const i0.Value.absent(),
                i0.Value<String?> description = const i0.Value.absent(),
                i0.Value<bool> isAutoGenerated = const i0.Value.absent(),
                i0.Value<DateTime> createdAt = const i0.Value.absent(),
              }) => i1.StockEventCompanion(
                id: id,
                symbol: symbol,
                eventType: eventType,
                eventDate: eventDate,
                title: title,
                description: description,
                isAutoGenerated: isAutoGenerated,
                createdAt: createdAt,
              ),
          createCompanionCallback:
              ({
                i0.Value<int> id = const i0.Value.absent(),
                i0.Value<String?> symbol = const i0.Value.absent(),
                required String eventType,
                required DateTime eventDate,
                required String title,
                i0.Value<String?> description = const i0.Value.absent(),
                i0.Value<bool> isAutoGenerated = const i0.Value.absent(),
                i0.Value<DateTime> createdAt = const i0.Value.absent(),
              }) => i1.StockEventCompanion.insert(
                id: id,
                symbol: symbol,
                eventType: eventType,
                eventDate: eventDate,
                title: title,
                description: description,
                isAutoGenerated: isAutoGenerated,
                createdAt: createdAt,
              ),
          withReferenceMapper: (p0) => p0
              .map((e) => (e.readTable(table), i0.BaseReferences(db, table, e)))
              .toList(),
          prefetchHooksCallback: null,
        ),
      );
}

typedef $$StockEventTableProcessedTableManager =
    i0.ProcessedTableManager<
      i0.GeneratedDatabase,
      i1.$StockEventTable,
      i1.StockEventEntry,
      i1.$$StockEventTableFilterComposer,
      i1.$$StockEventTableOrderingComposer,
      i1.$$StockEventTableAnnotationComposer,
      $$StockEventTableCreateCompanionBuilder,
      $$StockEventTableUpdateCompanionBuilder,
      (
        i1.StockEventEntry,
        i0.BaseReferences<
          i0.GeneratedDatabase,
          i1.$StockEventTable,
          i1.StockEventEntry
        >,
      ),
      i1.StockEventEntry,
      i0.PrefetchHooks Function()
    >;
i0.Index get idxStockEventDate => i0.Index(
  'idx_stock_event_date',
  'CREATE INDEX idx_stock_event_date ON stock_event (event_date)',
);

class $StockEventTable extends i2.StockEvent
    with i0.TableInfo<$StockEventTable, i1.StockEventEntry> {
  @override
  final i0.GeneratedDatabase attachedDatabase;
  final String? _alias;
  $StockEventTable(this.attachedDatabase, [this._alias]);
  static const i0.VerificationMeta _idMeta = const i0.VerificationMeta('id');
  @override
  late final i0.GeneratedColumn<int> id = i0.GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: i0.DriftSqlType.int,
    requiredDuringInsert: false,
    defaultConstraints: i0.GeneratedColumn.constraintIsAlways(
      'PRIMARY KEY AUTOINCREMENT',
    ),
  );
  static const i0.VerificationMeta _symbolMeta = const i0.VerificationMeta(
    'symbol',
  );
  @override
  late final i0.GeneratedColumn<String> symbol = i0.GeneratedColumn<String>(
    'symbol',
    aliasedName,
    true,
    type: i0.DriftSqlType.string,
    requiredDuringInsert: false,
  );
  static const i0.VerificationMeta _eventTypeMeta = const i0.VerificationMeta(
    'eventType',
  );
  @override
  late final i0.GeneratedColumn<String> eventType = i0.GeneratedColumn<String>(
    'event_type',
    aliasedName,
    false,
    type: i0.DriftSqlType.string,
    requiredDuringInsert: true,
  );
  static const i0.VerificationMeta _eventDateMeta = const i0.VerificationMeta(
    'eventDate',
  );
  @override
  late final i0.GeneratedColumn<DateTime> eventDate =
      i0.GeneratedColumn<DateTime>(
        'event_date',
        aliasedName,
        false,
        type: i0.DriftSqlType.dateTime,
        requiredDuringInsert: true,
      );
  static const i0.VerificationMeta _titleMeta = const i0.VerificationMeta(
    'title',
  );
  @override
  late final i0.GeneratedColumn<String> title = i0.GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: i0.DriftSqlType.string,
    requiredDuringInsert: true,
  );
  static const i0.VerificationMeta _descriptionMeta = const i0.VerificationMeta(
    'description',
  );
  @override
  late final i0.GeneratedColumn<String> description =
      i0.GeneratedColumn<String>(
        'description',
        aliasedName,
        true,
        type: i0.DriftSqlType.string,
        requiredDuringInsert: false,
      );
  static const i0.VerificationMeta _isAutoGeneratedMeta =
      const i0.VerificationMeta('isAutoGenerated');
  @override
  late final i0.GeneratedColumn<bool> isAutoGenerated =
      i0.GeneratedColumn<bool>(
        'is_auto_generated',
        aliasedName,
        false,
        type: i0.DriftSqlType.bool,
        requiredDuringInsert: false,
        defaultConstraints: i0.GeneratedColumn.constraintIsAlways(
          'CHECK ("is_auto_generated" IN (0, 1))',
        ),
        defaultValue: const i3.Constant(false),
      );
  static const i0.VerificationMeta _createdAtMeta = const i0.VerificationMeta(
    'createdAt',
  );
  @override
  late final i0.GeneratedColumn<DateTime> createdAt =
      i0.GeneratedColumn<DateTime>(
        'created_at',
        aliasedName,
        false,
        type: i0.DriftSqlType.dateTime,
        requiredDuringInsert: false,
        defaultValue: i3.currentDateAndTime,
      );
  @override
  List<i0.GeneratedColumn> get $columns => [
    id,
    symbol,
    eventType,
    eventDate,
    title,
    description,
    isAutoGenerated,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'stock_event';
  @override
  i0.VerificationContext validateIntegrity(
    i0.Insertable<i1.StockEventEntry> instance, {
    bool isInserting = false,
  }) {
    final context = i0.VerificationContext();
    final data = instance.toColumns(true);
    if (data.containsKey('id')) {
      context.handle(_idMeta, id.isAcceptableOrUnknown(data['id']!, _idMeta));
    }
    if (data.containsKey('symbol')) {
      context.handle(
        _symbolMeta,
        symbol.isAcceptableOrUnknown(data['symbol']!, _symbolMeta),
      );
    }
    if (data.containsKey('event_type')) {
      context.handle(
        _eventTypeMeta,
        eventType.isAcceptableOrUnknown(data['event_type']!, _eventTypeMeta),
      );
    } else if (isInserting) {
      context.missing(_eventTypeMeta);
    }
    if (data.containsKey('event_date')) {
      context.handle(
        _eventDateMeta,
        eventDate.isAcceptableOrUnknown(data['event_date']!, _eventDateMeta),
      );
    } else if (isInserting) {
      context.missing(_eventDateMeta);
    }
    if (data.containsKey('title')) {
      context.handle(
        _titleMeta,
        title.isAcceptableOrUnknown(data['title']!, _titleMeta),
      );
    } else if (isInserting) {
      context.missing(_titleMeta);
    }
    if (data.containsKey('description')) {
      context.handle(
        _descriptionMeta,
        description.isAcceptableOrUnknown(
          data['description']!,
          _descriptionMeta,
        ),
      );
    }
    if (data.containsKey('is_auto_generated')) {
      context.handle(
        _isAutoGeneratedMeta,
        isAutoGenerated.isAcceptableOrUnknown(
          data['is_auto_generated']!,
          _isAutoGeneratedMeta,
        ),
      );
    }
    if (data.containsKey('created_at')) {
      context.handle(
        _createdAtMeta,
        createdAt.isAcceptableOrUnknown(data['created_at']!, _createdAtMeta),
      );
    }
    return context;
  }

  @override
  Set<i0.GeneratedColumn> get $primaryKey => {id};
  @override
  i1.StockEventEntry map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return i1.StockEventEntry(
      id: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      symbol: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.string,
        data['${effectivePrefix}symbol'],
      ),
      eventType: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.string,
        data['${effectivePrefix}event_type'],
      )!,
      eventDate: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.dateTime,
        data['${effectivePrefix}event_date'],
      )!,
      title: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.string,
        data['${effectivePrefix}title'],
      )!,
      description: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.string,
        data['${effectivePrefix}description'],
      ),
      isAutoGenerated: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.bool,
        data['${effectivePrefix}is_auto_generated'],
      )!,
      createdAt: attachedDatabase.typeMapping.read(
        i0.DriftSqlType.dateTime,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  $StockEventTable createAlias(String alias) {
    return $StockEventTable(attachedDatabase, alias);
  }
}

class StockEventEntry extends i0.DataClass
    implements i0.Insertable<i1.StockEventEntry> {
  /// 自動遞增 ID
  final int id;

  /// 股票代碼（可為空，允許純個人備忘事件）
  final String? symbol;

  /// 事件類型：EX_DIVIDEND, EX_RIGHTS, EARNINGS, CUSTOM
  final String eventType;

  /// 事件日期
  final DateTime eventDate;

  /// 事件標題
  final String title;

  /// 事件描述/備註
  final String? description;

  /// 是否為系統自動產生
  final bool isAutoGenerated;

  /// 建立時間
  final DateTime createdAt;
  const StockEventEntry({
    required this.id,
    this.symbol,
    required this.eventType,
    required this.eventDate,
    required this.title,
    this.description,
    required this.isAutoGenerated,
    required this.createdAt,
  });
  @override
  Map<String, i0.Expression> toColumns(bool nullToAbsent) {
    final map = <String, i0.Expression>{};
    map['id'] = i0.Variable<int>(id);
    if (!nullToAbsent || symbol != null) {
      map['symbol'] = i0.Variable<String>(symbol);
    }
    map['event_type'] = i0.Variable<String>(eventType);
    map['event_date'] = i0.Variable<DateTime>(eventDate);
    map['title'] = i0.Variable<String>(title);
    if (!nullToAbsent || description != null) {
      map['description'] = i0.Variable<String>(description);
    }
    map['is_auto_generated'] = i0.Variable<bool>(isAutoGenerated);
    map['created_at'] = i0.Variable<DateTime>(createdAt);
    return map;
  }

  i1.StockEventCompanion toCompanion(bool nullToAbsent) {
    return i1.StockEventCompanion(
      id: i0.Value(id),
      symbol: symbol == null && nullToAbsent
          ? const i0.Value.absent()
          : i0.Value(symbol),
      eventType: i0.Value(eventType),
      eventDate: i0.Value(eventDate),
      title: i0.Value(title),
      description: description == null && nullToAbsent
          ? const i0.Value.absent()
          : i0.Value(description),
      isAutoGenerated: i0.Value(isAutoGenerated),
      createdAt: i0.Value(createdAt),
    );
  }

  factory StockEventEntry.fromJson(
    Map<String, dynamic> json, {
    i0.ValueSerializer? serializer,
  }) {
    serializer ??= i0.driftRuntimeOptions.defaultSerializer;
    return StockEventEntry(
      id: serializer.fromJson<int>(json['id']),
      symbol: serializer.fromJson<String?>(json['symbol']),
      eventType: serializer.fromJson<String>(json['eventType']),
      eventDate: serializer.fromJson<DateTime>(json['eventDate']),
      title: serializer.fromJson<String>(json['title']),
      description: serializer.fromJson<String?>(json['description']),
      isAutoGenerated: serializer.fromJson<bool>(json['isAutoGenerated']),
      createdAt: serializer.fromJson<DateTime>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({i0.ValueSerializer? serializer}) {
    serializer ??= i0.driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'symbol': serializer.toJson<String?>(symbol),
      'eventType': serializer.toJson<String>(eventType),
      'eventDate': serializer.toJson<DateTime>(eventDate),
      'title': serializer.toJson<String>(title),
      'description': serializer.toJson<String?>(description),
      'isAutoGenerated': serializer.toJson<bool>(isAutoGenerated),
      'createdAt': serializer.toJson<DateTime>(createdAt),
    };
  }

  i1.StockEventEntry copyWith({
    int? id,
    i0.Value<String?> symbol = const i0.Value.absent(),
    String? eventType,
    DateTime? eventDate,
    String? title,
    i0.Value<String?> description = const i0.Value.absent(),
    bool? isAutoGenerated,
    DateTime? createdAt,
  }) => i1.StockEventEntry(
    id: id ?? this.id,
    symbol: symbol.present ? symbol.value : this.symbol,
    eventType: eventType ?? this.eventType,
    eventDate: eventDate ?? this.eventDate,
    title: title ?? this.title,
    description: description.present ? description.value : this.description,
    isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    createdAt: createdAt ?? this.createdAt,
  );
  StockEventEntry copyWithCompanion(i1.StockEventCompanion data) {
    return StockEventEntry(
      id: data.id.present ? data.id.value : this.id,
      symbol: data.symbol.present ? data.symbol.value : this.symbol,
      eventType: data.eventType.present ? data.eventType.value : this.eventType,
      eventDate: data.eventDate.present ? data.eventDate.value : this.eventDate,
      title: data.title.present ? data.title.value : this.title,
      description: data.description.present
          ? data.description.value
          : this.description,
      isAutoGenerated: data.isAutoGenerated.present
          ? data.isAutoGenerated.value
          : this.isAutoGenerated,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('StockEventEntry(')
          ..write('id: $id, ')
          ..write('symbol: $symbol, ')
          ..write('eventType: $eventType, ')
          ..write('eventDate: $eventDate, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('isAutoGenerated: $isAutoGenerated, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    symbol,
    eventType,
    eventDate,
    title,
    description,
    isAutoGenerated,
    createdAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is i1.StockEventEntry &&
          other.id == this.id &&
          other.symbol == this.symbol &&
          other.eventType == this.eventType &&
          other.eventDate == this.eventDate &&
          other.title == this.title &&
          other.description == this.description &&
          other.isAutoGenerated == this.isAutoGenerated &&
          other.createdAt == this.createdAt);
}

class StockEventCompanion extends i0.UpdateCompanion<i1.StockEventEntry> {
  final i0.Value<int> id;
  final i0.Value<String?> symbol;
  final i0.Value<String> eventType;
  final i0.Value<DateTime> eventDate;
  final i0.Value<String> title;
  final i0.Value<String?> description;
  final i0.Value<bool> isAutoGenerated;
  final i0.Value<DateTime> createdAt;
  const StockEventCompanion({
    this.id = const i0.Value.absent(),
    this.symbol = const i0.Value.absent(),
    this.eventType = const i0.Value.absent(),
    this.eventDate = const i0.Value.absent(),
    this.title = const i0.Value.absent(),
    this.description = const i0.Value.absent(),
    this.isAutoGenerated = const i0.Value.absent(),
    this.createdAt = const i0.Value.absent(),
  });
  StockEventCompanion.insert({
    this.id = const i0.Value.absent(),
    this.symbol = const i0.Value.absent(),
    required String eventType,
    required DateTime eventDate,
    required String title,
    this.description = const i0.Value.absent(),
    this.isAutoGenerated = const i0.Value.absent(),
    this.createdAt = const i0.Value.absent(),
  }) : eventType = i0.Value(eventType),
       eventDate = i0.Value(eventDate),
       title = i0.Value(title);
  static i0.Insertable<i1.StockEventEntry> custom({
    i0.Expression<int>? id,
    i0.Expression<String>? symbol,
    i0.Expression<String>? eventType,
    i0.Expression<DateTime>? eventDate,
    i0.Expression<String>? title,
    i0.Expression<String>? description,
    i0.Expression<bool>? isAutoGenerated,
    i0.Expression<DateTime>? createdAt,
  }) {
    return i0.RawValuesInsertable({
      if (id != null) 'id': id,
      if (symbol != null) 'symbol': symbol,
      if (eventType != null) 'event_type': eventType,
      if (eventDate != null) 'event_date': eventDate,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (isAutoGenerated != null) 'is_auto_generated': isAutoGenerated,
      if (createdAt != null) 'created_at': createdAt,
    });
  }

  i1.StockEventCompanion copyWith({
    i0.Value<int>? id,
    i0.Value<String?>? symbol,
    i0.Value<String>? eventType,
    i0.Value<DateTime>? eventDate,
    i0.Value<String>? title,
    i0.Value<String?>? description,
    i0.Value<bool>? isAutoGenerated,
    i0.Value<DateTime>? createdAt,
  }) {
    return i1.StockEventCompanion(
      id: id ?? this.id,
      symbol: symbol ?? this.symbol,
      eventType: eventType ?? this.eventType,
      eventDate: eventDate ?? this.eventDate,
      title: title ?? this.title,
      description: description ?? this.description,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  Map<String, i0.Expression> toColumns(bool nullToAbsent) {
    final map = <String, i0.Expression>{};
    if (id.present) {
      map['id'] = i0.Variable<int>(id.value);
    }
    if (symbol.present) {
      map['symbol'] = i0.Variable<String>(symbol.value);
    }
    if (eventType.present) {
      map['event_type'] = i0.Variable<String>(eventType.value);
    }
    if (eventDate.present) {
      map['event_date'] = i0.Variable<DateTime>(eventDate.value);
    }
    if (title.present) {
      map['title'] = i0.Variable<String>(title.value);
    }
    if (description.present) {
      map['description'] = i0.Variable<String>(description.value);
    }
    if (isAutoGenerated.present) {
      map['is_auto_generated'] = i0.Variable<bool>(isAutoGenerated.value);
    }
    if (createdAt.present) {
      map['created_at'] = i0.Variable<DateTime>(createdAt.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('StockEventCompanion(')
          ..write('id: $id, ')
          ..write('symbol: $symbol, ')
          ..write('eventType: $eventType, ')
          ..write('eventDate: $eventDate, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('isAutoGenerated: $isAutoGenerated, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }
}

i0.Index get idxStockEventSymbol => i0.Index(
  'idx_stock_event_symbol',
  'CREATE INDEX idx_stock_event_symbol ON stock_event (symbol)',
);
